Changed build-and-deploy-backend workflow

diff --git a/.github/workflows/build-and-deploy-backend.yaml b/.github/workflows/build-and-deploy-backend.yaml
--- a/.github/workflows/build-and-deploy-backend.yaml
+++ b/.github/workflows/build-and-deploy-backend.yaml
@@ -54,7 +54,7 @@ jobs:
       #     path: schema.yaml
 
       - name: Configure AWS Credentials
-        uses: aws-actions/configure-aws-credentials@v1
+        uses: aws-actions/configure-aws-credentials@v4
         with:
           aws-access-key-id: ${{ secrets.AWS_BACKEND_DEPLOY_ACCESS_KEY_ID }}
           aws-secret-access-key: ${{ secrets.AWS_BACKEND_DEPLOY_SECRET_ACCESS_KEY }}
@@ -66,40 +66,40 @@ jobs:
         with:
           task-definition-arn: ${{ vars.ECS_TASK_DEFINITION_APPLY_MIGRATIONS_ARN }}
           container-name: ${{ vars.APPLY_MIGRATIONS_CONTAINER_NAME }}
-          image: 357844151986.dkr.ecr.us-west-1.amazonaws.com/fondo/backend:0.0.29
+          image: 357844151986.dkr.ecr.us-west-1.amazonaws.com/fondo/backend:0.0.30
 
-      # - name: Run ECS Task to Apply Migrations
-      #   id: run-ecs-task-apply-migrations
-      #   run: |
-      #     TASK_MIGRATIONS_ARN=$(aws ecs run-task \
-      #       --cluster ${{ vars.ECS_CLUSTER }} \
-      #       --launch-type EC2 \
-      #       --task-definition ${{ vars.ECS_TASK_DEFINITION_APPLY_MIGRATIONS_ARN }} \
-      #       --query 'tasks[0].taskArn' \
-      #       --output text)
+      - name: Run ECS Task to Apply Migrations
+        id: run-ecs-task-apply-migrations
+        run: |
+          TASK_MIGRATIONS_ARN=$(aws ecs run-task \
+            --cluster ${{ vars.ECS_CLUSTER }} \
+            --launch-type EC2 \
+            --task-definition ${{ steps.task-def-apply-migrations.outputs.task-definition }} \
+            --query 'tasks[0].taskArn' \
+            --output text)
 
-      #     echo "Started ECS task with ARN: $TASK_MIGRATIONS_ARN"
-      #     echo "TASK_MIGRATIONS_ARN=$TASK_MIGRATIONS_ARN" >> $GITHUB_ENV
+          echo "Started ECS task with ARN: $TASK_MIGRATIONS_ARN"
+          echo "TASK_MIGRATIONS_ARN=$TASK_MIGRATIONS_ARN" >> $GITHUB_ENV
 
-      # - name: Wait for Task Completion
-      #   id: wait-for-ecs-task
-      #   run: |
-      #     while true; do
-      #       STATUS=$(aws ecs describe-tasks --cluster ${{ vars.ECS_CLUSTER }} --tasks ${{ env.TASK_MIGRATIONS_ARN }} --query 'tasks[0].lastStatus' --output text)
-      #       echo "Task status: $STATUS"
-      #       if [[ "$STATUS" == "STOPPED" ]]; then
-      #         BREAK_CODE=$(aws ecs describe-tasks --cluster ${{ vars.ECS_CLUSTER }} --tasks ${{ env.TASK_MIGRATIONS_ARN }} --query 'tasks[0].containers[0].exitCode' --output text)
-      #         echo "Task exit code: $BREAK_CODE"
-      #         if [[ "$BREAK_CODE" -eq 0 ]]; then
-      #           echo "Migrations applied successfully!"
-      #           exit 0
-      #         else
-      #           echo "Migrations failed!"
-      #           exit 1
-      #         fi
-      #       fi
-      #       sleep 10
-      #     done
+      - name: Wait for Task Completion
+        id: wait-for-ecs-task
+        run: |
+          while true; do
+            STATUS=$(aws ecs describe-tasks --cluster ${{ vars.ECS_CLUSTER }} --tasks ${{ env.TASK_MIGRATIONS_ARN }} --query 'tasks[0].lastStatus' --output text)
+            echo "Task status: $STATUS"
+            if [[ "$STATUS" == "STOPPED" ]]; then
+              BREAK_CODE=$(aws ecs describe-tasks --cluster ${{ vars.ECS_CLUSTER }} --tasks ${{ env.TASK_MIGRATIONS_ARN }} --query 'tasks[0].containers[0].exitCode' --output text)
+              echo "Task exit code: $BREAK_CODE"
+              if [[ "$BREAK_CODE" -eq 0 ]]; then
+                echo "Migrations applied successfully!"
+                exit 0
+              else
+                echo "Migrations failed!"
+                exit 1
+              fi
+            fi
+            sleep 10
+          done
 
       # - name: Fill in the new image ID in the Amazon ECS task definition web
       #   id: task-def-web
